# CUSTOM FENRIR PROPERTIES
ProjectName: "coinbase/fenrir/examples/hello"
ConfigName: "development"

# SAM TEMPLATE
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello SAM

Resources:
  helloAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration: REGIONAL
  hello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: hello.lambda
      Runtime: go1.x
      Timeout: 5
      Role: default@lambda
      Events:
        hi:
          Type: Api
          Properties:
            RestApiId: !Ref helloAPI
            Path: /hello
            Method: GET
        sns:
          Type: SNS
          Properties:
            Topic: test-sns

  helloTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub "https://${helloAPI}.execute-api.${AWS::Region}.amazonaws.com/dev"
