# CUSTOM FENRIR PROPERTIES
ProjectName: "coinbase/fenrir/albcf/hello"
ConfigName: "development"

# SAM TEMPLATE
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hello SAM

Resources:
  helloAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration: REGIONAL
  basicHello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: hello.lambda
      Runtime: go1.x
      Timeout: 5
      Role: default@lambda
  hello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: hello.lambda
      Runtime: go1.x
      Timeout: 5
      Policies:
      - LambdaInvokePolicy:
          FunctionName: !Ref basicHello
      - DynamoDBCrudPolicy:
          TableName: !Ref helloTable
      - SQSPollerPolicy:
          QueueName: !Ref helloQueue
      - VPCAccessPolicy: {}
      Events:
        hi:
          Type: Api
          Properties:
            RestApiId: !Ref helloAPI
            Path: /hello
            Method: GET
  cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: www.example.com
          Id: myCustomOrigin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: myCustomOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
  helloTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  helloQueue:
    Type: AWS::SQS::Queue

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub "https://${helloAPI}.execute-api.${AWS::Region}.amazonaws.com/dev"
